import { fromJSON } from "postcss"
import { EditProfile } from "./Profile/comps"

export { default as LandingPageNav } from "./LandingPage/LandingPageNav"
export { default as GenerateQuotation } from "./LandingPage/GenerateQuotation"
export { default as ServicesCards } from "./LandingPage/ServicesCards"
export { default as MapView } from "./LandingPage/MapView"
export { default as Reviews } from "./LandingPage/Reviews"
export { default as Questions } from "./LandingPage/Questions"

export { default as Footer } from "./Footer"
export { default as SignupOne } from "./SignupOne"
export { default as SignupTwo } from "./SignupTwo"

export { default as VerificationOne } from "./VerificationOne"
export { default as VerificationTwo } from "./VerificationTwo"
export { default as AccountOne } from "./AccountOne"
export { default as AccountTwo } from "./AccountTwo"
export { default as SelectCityDropdown } from "./SelectCityDropdown"


export { default as HomeNav } from "./Home/HomeNav"
export { default as NavMenu } from "./Home/NavMenu"
export { default as CTASection } from "./Home/CTASection"
export { default as DownLoadCTA } from "./Home/DownLoadCTA"
export { default as PackersAndMoversSection } from "./Home/PackersAndMoversSection"
export { default as InfoSection } from "./Home/InfoSection"
export { default as ShifitingProcess } from "./Home/ShiftingProcess"
export { default as PricingSection } from "./Home/PricingSection"
export { default as Cities } from "./Home/Cities"
export { default as FAQs } from "./Home/FAQs"
export { default as PSignupTwo} from "./Packers&Movers/PSignupTwo"
export {default as PAccountTwo} from "./Packers&Movers/PAccountTwo"
export {default as EditProfileComponent} from "./Profile/EditProfileComponent"
export { default as ProfileInfo } from "./Profile/ProfileInfo"
export { default as EmailVerify} from "./Packers&Movers/EmailVerify"
export {default as CardVerify} from "./Packers&Movers/CardVerify"
export {default as PackersNav} from "./Packers&Movers/PackersNav";
export {default as Calendar} from "./Packers&Movers/Calendar"
export { default as OrderRequest } from "./Packers&Movers/OrderRequest"
export {default as OrderOngoing} from "./Packers&Movers/OrderOngoingTwo"
export {default as ProgressButton} from "./Packers&Movers/ProgressButton"
export {default as LinkAccount} from "./Packers&Movers/LinkAccount"
export {default as EarningCards} from "./Packers&Movers/EarningCards"
export {default as PAccountDetails} from "./Packers&Movers/PAccountDetails"
export {default as PEditProfileComponent} from "./Packers&Movers/PEditProfileComponent"
export {default as VerticalShippingIndicator} from "./Packers&Movers/VerticalShippingIndicator"


