export { default as LandingPageNav } from "./LandingPageNav"
export { default as GenerateQuotation } from "./GenerateQuotation"
export { default as ServicesCards } from "./ServicesCards"
export { default as MapView } from "./MapView"
export { default as Reviews } from "./Reviews"
export { default as Questions } from "./Questions"
export { default as Footer } from "./Footer"
export { default as SignupOne } from "./SignupOne"
export { default as SignupTwo } from "./SignupTwo"
export { default as SignupThree } from "./SignupThree"
export { default as VerificationSection1 } from "./VerificationOne"
export { default as VerificationSection2 } from "./VerificationTwo"

export { default as SignupSection1 } from "./SignupSection1"
export { default as SignupSection2 } from "./SignupSection2"
export { default as SelectCityDropdown } from "./SelectCityDropdown"
export { default as HomeNav } from "./HomeNav"
export { default as NavMenu } from "./NavMenu"
export { default as CTASection } from "./CTASection"
export { default as DownLoadCTA } from "./DownLoadCTA"
export { default as PackersAndMoversSection } from "./PackersAndMoversSection"
export { default as InfoSection } from "./InfoSection"
export { default as ShifitingProcess } from "./ShiftingProcess"
export { default as PricingSection } from "./PricingSection"
export { default as Cities } from "./Cities"
export { default as FAQs } from "./FAQs"

